Adds feature to configure keycloak server with Scopes
TNG/keycloak-mock pull request #128
Opened 2022-09-16 17:50 UTC by mdanish98

This library is indeed really useful.
I was using this library to mock keycloak authorization token behavior. But one use case it was missing like when there is an implementation for getting authorization token with normal OAuth2 request using custom getAccessToken method. The scenario is like I have a project which has a method to provide authorization and it just takes clientId, clientSecret and tokenUrl and it has its own implementation to request JWT token. Here I have to check whether it is able to successfully get the access token and then able to provide access to the secured registry, and the secured registry checks for the required scopes needed to perform certain action (Read/Write etc).
So for this there is a need to configure the realm with clientScopes while configuring the server and by not using TokenConfig. 
I have added this feature to initialize and start KeyCloakMock server with clientScopes. I have also added the required test cases to cover this implementation.

Please let me know incase you need further information.

Thanks
Signed-off-by: Mohammad Ghazanfar Ali Danish <mdanish98@gmail.com>

2022-09-20 12:19 UTC, mdanish98 commented
Dear @ostrya

Did you had some time to check this PR ?
Actually I have another PR on my other project which is dependent on this. If this change is merged that would be easy to update the dependent PR.

Please let me know incase of any further information.

Thanks and Regards

2022-10-14 08:02 UTC, ostrya requested changes
Sorry for the late reply. I like your change, but I have a suggestion so we can avoid manipulating static variables.

2022-10-16 20:29 UTC, mdanish98 commented on mock/src/main/java/com/tngtech/keycloakmock/api/ServerConfig.java
> +      TokenConfig.addClientScopes(scope);
Thanks for your suggestions @ostrya 

As per your suggestions I have updated the pull request. Following are the changes I did:
- Added defaultScopes configuration in ServerConfig
- Removed withClientScopes method in ServerConfig
- Moved the openid scope from the TokenConfig to ServerConfig
- Removed the default value scope check from TokenConfigTest (default_values_are_used) as now default value of scope is configured via ServerConfig
- Modified the TokenGeneratorTest (config_is_correctly_applied) in such a way that it only checks the scope configured and not the defaultScope
- Now the defaultScope (openid) is added when Keycloakmock Server is instantiated
- Added additional test case in KeycloakMockTest to check if the server is started without using withDefaultScopes then by default it should contain 'openid' scope

As you know moving the default scope "openid" from TokenConfig to ServerConfig is a breaking change, so thatswhy I have to adapt few test cases inorder to fit with current changes.

Please let me know if you need further changes or if I misunderstood something.

2022-10-16 20:31 UTC, mdanish98 commented on example-backend/bin/.gitignore
> +/main/
Thanks for your suggestions @ostrya

I have corrected this and updated the pull request.
Please let me know if you need further changes.

2023-01-17 15:31 UTC, mdanish98 commented
Dear @ostrya @mrmarbury @Achimh3011 @aaschmid ,

Actually we are dependent on this change and our project which is [Eclipse Basyx](https://github.com/eclipse-basyx/basyx-java-sdk) an **Industry 4.0** project is pending due to this pull request. 

I request you to please look into that change and merge it so that we can use it in our project.

2023-01-17 19:24 UTC, ostrya commented
Hi, sorry for the long delay. I had a really busy November and must then have lost track of this PR. I will have a look now.

2023-01-17 19:46 UTC, ostrya requested changes

2023-01-18 20:24 UTC, mdanish98 commented on mock/src/main/java/com/tngtech/keycloakmock/api/ServerConfig.java
> +   * The default scopes used in issuer claim.
Updated this in new commit

2023-01-18 20:24 UTC, mdanish98 commented on mock/src/main/java/com/tngtech/keycloakmock/api/ServerConfig.java
> +     * <p>Set of client scopes to be configured. Default scope is 'openid'.
Updated this in new commit

2023-01-18 20:25 UTC, mdanish98 commented on mock/src/main/java/com/tngtech/keycloakmock/api/TokenConfig.java
> -      scope.add("openid");
Updated the Javadoc in new commit

2023-01-18 20:37 UTC, mdanish98 commented
Dear @ostrya 

Many thanks for your suggestion I updated all the changes you requested.
One remark regarding the "please use a solution similar to the "resourcesToMapRolesTo" parameter:" comment:
As per your remarks I created a named singleton inside ServerModule. I tried to inject the named parameter into TokenGenerator's constructor but it was not working because the TokenGenerator is being used in SignatureComponent and due to this it was throwing error as [[Dagger/MissingBinding]](error: [Dagger/MissingBinding] @javax.inject.Named). So I thought that would be a major change because I might have to include the ServerModule.class in SignatureComponent like @Component(modules = {KeyModule.class, ServerModule.class}) . And thatswhy I did the same thing you suggested in TokenHelper class instead, i.e. how "resourcesToMapRolesTo" is also implemented.

Please let me know if this is fine otherwise I will do it in TokenGenerator.

Please review it and let me know for further changes.

Thanks and Regards

2023-01-19 07:29 UTC, ostrya reviewed
Yes, the approach to inject the scopes is much better. And it's fine to inject the scopes in the token helper instead.

I have just two minor remarks on the tests, otherwise it looks good now.

2023-01-19 07:29 UTC, ostrya commented on mock/src/test/java/com/tngtech/keycloakmock/api/KeycloakMockTest.java
> +    assertThat(scope.size()).isEqualTo(3);
Cosmetic change:
```suggestion
    assertThat(scope).hasSize(3);
```

2023-01-19 07:29 UTC, ostrya commented on mock/src/test/java/com/tngtech/keycloakmock/api/TokenConfigTest.java
> -    assertThat(config.getScope()).isEqualTo("openid");
To document the new behavior, maybe assert the scope is empty by default? I.e.

```
assertThat(config.getScope()).isEmpty();
```

2023-01-19 07:33 UTC, ostrya approved these changes

2023-01-19 07:34 UTC, ostrya commented
I'll just merge and adapt the tests on the main branch.

2023-01-19 07:34 UTC, merged