support confidential clients that authenticate using form fields
TNG/keycloak-mock pull request #99
Opened 2021-09-13 19:17 UTC by marcelocamanho

Fixes https://github.com/TNG/keycloak-mock/issues/98

This will allow confidential clients that use a form based approach instead of only using Basic auth.

2021-09-21 17:52 UTC, marcelocamanho commented
hi @ostrya , any chance we can this reviewed please ? thank you :)

2021-09-24 07:05 UTC, ostrya requested changes
Overall looks good, but please check your formatting (see https://github.com/TNG/keycloak-mock/pull/99/checks?check_run_id=3696977760).

2021-09-24 07:06 UTC, ostrya commented
And sorry for the delay, I was rather occupied with day-to-day business.

2021-11-12 10:33 UTC, ostrya approved these changes

2021-11-12 10:47 UTC, ostrya commented
@marcelocamanho can you please rebase your changes and remove the merge commit?

2021-12-10 08:50 UTC, ostrya commented
@marcelocamanho I have taken the liberty to rebase your changes onto the latest changes and remove the merge commit.

2021-12-10 09:01 UTC, merged